<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Indonesia', 'code' => 'IDN', 'is_indonesia' => true, 'phone_code' => '+62'],
            ['name' => 'Afghanistan', 'code' => 'AFG', 'is_indonesia' => false, 'phone_code' => '+93'],
            ['name' => 'Albania', 'code' => 'ALB', 'is_indonesia' => false, 'phone_code' => '+355'],
            ['name' => 'Algeria', 'code' => 'DZA', 'is_indonesia' => false, 'phone_code' => '+213'],
            ['name' => 'Argentina', 'code' => 'ARG', 'is_indonesia' => false, 'phone_code' => '+54'],
            ['name' => 'Australia', 'code' => 'AUS', 'is_indonesia' => false, 'phone_code' => '+61'],
            ['name' => 'Austria', 'code' => 'AUT', 'is_indonesia' => false, 'phone_code' => '+43'],
            ['name' => 'Bahrain', 'code' => 'BHR', 'is_indonesia' => false, 'phone_code' => '+973'],
            ['name' => 'Bangladesh', 'code' => 'BGD', 'is_indonesia' => false, 'phone_code' => '+880'],
            ['name' => 'Belgium', 'code' => 'BEL', 'is_indonesia' => false, 'phone_code' => '+32'],
            ['name' => 'Brazil', 'code' => 'BRA', 'is_indonesia' => false, 'phone_code' => '+55'],
            ['name' => 'Brunei', 'code' => 'BRN', 'is_indonesia' => false, 'phone_code' => '+673'],
            ['name' => 'Cambodia', 'code' => 'KHM', 'is_indonesia' => false, 'phone_code' => '+855'],
            ['name' => 'Canada', 'code' => 'CAN', 'is_indonesia' => false, 'phone_code' => '+1'],
            ['name' => 'Chile', 'code' => 'CHL', 'is_indonesia' => false, 'phone_code' => '+56'],
            ['name' => 'China', 'code' => 'CHN', 'is_indonesia' => false, 'phone_code' => '+86'],
            ['name' => 'Colombia', 'code' => 'COL', 'is_indonesia' => false, 'phone_code' => '+57'],
            ['name' => 'Czech Republic', 'code' => 'CZE', 'is_indonesia' => false, 'phone_code' => '+420'],
            ['name' => 'Denmark', 'code' => 'DNK', 'is_indonesia' => false, 'phone_code' => '+45'],
            ['name' => 'Egypt', 'code' => 'EGY', 'is_indonesia' => false, 'phone_code' => '+20'],
            ['name' => 'Finland', 'code' => 'FIN', 'is_indonesia' => false, 'phone_code' => '+358'],
            ['name' => 'France', 'code' => 'FRA', 'is_indonesia' => false, 'phone_code' => '+33'],
            ['name' => 'Germany', 'code' => 'DEU', 'is_indonesia' => false, 'phone_code' => '+49'],
            ['name' => 'Greece', 'code' => 'GRC', 'is_indonesia' => false, 'phone_code' => '+30'],
            ['name' => 'Hong Kong', 'code' => 'HKG', 'is_indonesia' => false, 'phone_code' => '+852'],
            ['name' => 'Hungary', 'code' => 'HUN', 'is_indonesia' => false, 'phone_code' => '+36'],
            ['name' => 'India', 'code' => 'IND', 'is_indonesia' => false, 'phone_code' => '+91'],
            ['name' => 'Iran', 'code' => 'IRN', 'is_indonesia' => false, 'phone_code' => '+98'],
            ['name' => 'Iraq', 'code' => 'IRQ', 'is_indonesia' => false, 'phone_code' => '+964'],
            ['name' => 'Ireland', 'code' => 'IRL', 'is_indonesia' => false, 'phone_code' => '+353'],
            ['name' => 'Israel', 'code' => 'ISR', 'is_indonesia' => false, 'phone_code' => '+972'],
            ['name' => 'Italy', 'code' => 'ITA', 'is_indonesia' => false, 'phone_code' => '+39'],
            ['name' => 'Japan', 'code' => 'JPN', 'is_indonesia' => false, 'phone_code' => '+81'],
            ['name' => 'Jordan', 'code' => 'JOR', 'is_indonesia' => false, 'phone_code' => '+962'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ', 'is_indonesia' => false, 'phone_code' => '+7'],
            ['name' => 'Kenya', 'code' => 'KEN', 'is_indonesia' => false, 'phone_code' => '+254'],
            ['name' => 'Kuwait', 'code' => 'KWT', 'is_indonesia' => false, 'phone_code' => '+965'],
            ['name' => 'Laos', 'code' => 'LAO', 'is_indonesia' => false, 'phone_code' => '+856'],
            ['name' => 'Lebanon', 'code' => 'LBN', 'is_indonesia' => false, 'phone_code' => '+961'],
            ['name' => 'Libya', 'code' => 'LBY', 'is_indonesia' => false, 'phone_code' => '+218'],
            ['name' => 'Luxembourg', 'code' => 'LUX', 'is_indonesia' => false, 'phone_code' => '+352'],
            ['name' => 'Macau', 'code' => 'MAC', 'is_indonesia' => false, 'phone_code' => '+853'],
            ['name' => 'Malaysia', 'code' => 'MYS', 'is_indonesia' => false, 'phone_code' => '+60'],
            ['name' => 'Maldives', 'code' => 'MDV', 'is_indonesia' => false, 'phone_code' => '+960'],
            ['name' => 'Mexico', 'code' => 'MEX', 'is_indonesia' => false, 'phone_code' => '+52'],
            ['name' => 'Mongolia', 'code' => 'MNG', 'is_indonesia' => false, 'phone_code' => '+976'],
            ['name' => 'Morocco', 'code' => 'MAR', 'is_indonesia' => false, 'phone_code' => '+212'],
            ['name' => 'Myanmar', 'code' => 'MMR', 'is_indonesia' => false, 'phone_code' => '+95'],
            ['name' => 'Nepal', 'code' => 'NPL', 'is_indonesia' => false, 'phone_code' => '+977'],
            ['name' => 'Netherlands', 'code' => 'NLD', 'is_indonesia' => false, 'phone_code' => '+31'],
            ['name' => 'New Zealand', 'code' => 'NZL', 'is_indonesia' => false, 'phone_code' => '+64'],
            ['name' => 'Nigeria', 'code' => 'NGA', 'is_indonesia' => false, 'phone_code' => '+234'],
            ['name' => 'Norway', 'code' => 'NOR', 'is_indonesia' => false, 'phone_code' => '+47'],
            ['name' => 'Oman', 'code' => 'OMN', 'is_indonesia' => false, 'phone_code' => '+968'],
            ['name' => 'Pakistan', 'code' => 'PAK', 'is_indonesia' => false, 'phone_code' => '+92'],
            ['name' => 'Peru', 'code' => 'PER', 'is_indonesia' => false, 'phone_code' => '+51'],
            ['name' => 'Philippines', 'code' => 'PHL', 'is_indonesia' => false, 'phone_code' => '+63'],
            ['name' => 'Poland', 'code' => 'POL', 'is_indonesia' => false, 'phone_code' => '+48'],
            ['name' => 'Portugal', 'code' => 'PRT', 'is_indonesia' => false, 'phone_code' => '+351'],
            ['name' => 'Qatar', 'code' => 'QAT', 'is_indonesia' => false, 'phone_code' => '+974'],
            ['name' => 'Romania', 'code' => 'ROU', 'is_indonesia' => false, 'phone_code' => '+40'],
            ['name' => 'Russia', 'code' => 'RUS', 'is_indonesia' => false, 'phone_code' => '+7'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU', 'is_indonesia' => false, 'phone_code' => '+966'],
            ['name' => 'Serbia', 'code' => 'SRB', 'is_indonesia' => false, 'phone_code' => '+381'],
            ['name' => 'Singapore', 'code' => 'SGP', 'is_indonesia' => false, 'phone_code' => '+65'],
            ['name' => 'South Africa', 'code' => 'ZAF', 'is_indonesia' => false, 'phone_code' => '+27'],
            ['name' => 'South Korea', 'code' => 'KOR', 'is_indonesia' => false, 'phone_code' => '+82'],
            ['name' => 'Spain', 'code' => 'ESP', 'is_indonesia' => false, 'phone_code' => '+34'],
            ['name' => 'Sri Lanka', 'code' => 'LKA', 'is_indonesia' => false, 'phone_code' => '+94'],
            ['name' => 'Sweden', 'code' => 'SWE', 'is_indonesia' => false, 'phone_code' => '+46'],
            ['name' => 'Switzerland', 'code' => 'CHE', 'is_indonesia' => false, 'phone_code' => '+41'],
            ['name' => 'Syria', 'code' => 'SYR', 'is_indonesia' => false, 'phone_code' => '+963'],
            ['name' => 'Taiwan', 'code' => 'TWN', 'is_indonesia' => false, 'phone_code' => '+886'],
            ['name' => 'Thailand', 'code' => 'THA', 'is_indonesia' => false, 'phone_code' => '+66'],
            ['name' => 'Turkey', 'code' => 'TUR', 'is_indonesia' => false, 'phone_code' => '+90'],
            ['name' => 'Ukraine', 'code' => 'UKR', 'is_indonesia' => false, 'phone_code' => '+380'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE', 'is_indonesia' => false, 'phone_code' => '+971'],
            ['name' => 'United Kingdom', 'code' => 'GBR', 'is_indonesia' => false, 'phone_code' => '+44'],
            ['name' => 'United States', 'code' => 'USA', 'is_indonesia' => false, 'phone_code' => '+1'],
            ['name' => 'Venezuela', 'code' => 'VEN', 'is_indonesia' => false, 'phone_code' => '+58'],
            ['name' => 'Vietnam', 'code' => 'VNM', 'is_indonesia' => false, 'phone_code' => '+84'],
        ];

        foreach ($countries as $country) {
            Country::firstOrCreate(['code' => $country['code']], $country);
        }
    }
}
